package com.erwin.backend.enums;

public enum EstadoDocumento {
    BORRADOR,
    EN_REVISION,
    CORRECCION_REQUERIDA,
    APROBADO_POR_DIRECTOR,
    LISTO_PARA_TRIBUNAL,
    TRIBUNAL_ASIGNADO,
    SUSTENTACION_AGENDADA,
    SUSTENTADO,
    CERRADO_APROBADO,
    CERRADO_REPROBADO,
    ANTIPLAGIO_APROBADO,
    EN_PREDEFENSA,
    LISTO_SUSTENTACION
}